# Generated by Django 6.0 on 2026-02-13 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eventos',
            new_name='Evento',
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'verbose_name': 'Notificacion', 'verbose_name_plural': 'Notificaciones'},
        ),
    ]
