# Generated by Django 6.0.1 on 2026-02-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True),
        ),
    ]
