# Generated by Django 6.0.1 on 2026-02-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='fechainicio',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
