# Generated by Django 6.0.2 on 2026-02-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eventos',
            new_name='Evento',
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'verbose_name': 'Notificacion', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('A tiempo', 'A tiempo'), ('Tarde', 'Tarde'), ('Inasistencia', 'Inasistencia')], max_length=20),
        ),
    ]
