# Generated by Django 6.0.1 on 2026-02-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_usuario_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='estadoMatricula',
            field=models.TextField(blank=True, choices=[('Matriculado', 'Matriculado'), ('No Matriculado', 'No Matriculado'), ('Retirado', 'Retirado'), ('Graduado', 'Graduado'), ('Sancionado', 'Sancionado')], max_length=20, null=True, verbose_name='Estado de Matricula'),
        ),
    ]
