# Generated by Django 6.0.2 on 2026-02-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_eventos_evento_alter_notificacion_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='obsevaciones',
            new_name='observaciones',
        ),
    ]
