# Generated by Django 6.0.2 on 2026-02-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_categoria_nombre_alter_curso_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='odsevaciones',
            new_name='obsevaciones',
        ),
    ]
